motor:
  max_peak_rpm: 20000
  max_continuous_rpm: 13250

  max_continuous_current: 22.6
  max_peak_current: 66.0       

  max_continuous_power: 15400.0  
  max_peak_power: 35000.0      

  max_continuous_torque: 24.6
  max_peak_torque: 31.6

  kt_constant: 0.492     # Nm / A  Used to convert current to torque (and vice versa) (slighly lower than datasheet as the motor is used with less voltage)
  peak_duration: 120.0   # Não mexi
  fade_start: 0.95     # Fraction of max RPM at which to start fading torque to 0
  
  efficiency_map:
    2000:
      2: 0.930
      6: 0.938
      12: 0.908
      18: 0.874
      24: 0.841
    6000:
      2: 0.874
      6: 0.942
      12: 0.949
      18: 0.942
      24: 0.932
    10000:
      2: 0.862
      6: 0.942
      12: 0.957
      18: 0.957
      24: 0.953
    16000:
      2: 0.896
      6: 0.958
      12: 0.970
      18: 0.971
      24: 0.969
    20000:
      2: 0.912
      6: 0.965
      12: 0.976
      18: 0.976
      24: 0.974