var annotated_dup =
[
    [ "plots", "da/dc0/namespaceplots.html", [
      [ "plots", "d3/d43/namespaceplots_1_1plots.html", [
        [ "Cone", "db/d27/classplots_1_1plots_1_1_cone.html", "db/d27/classplots_1_1plots_1_1_cone" ],
        [ "Plots", "d8/dee/classplots_1_1plots_1_1_plots.html", "d8/dee/classplots_1_1plots_1_1_plots" ],
        [ "Pose", "d4/dc9/classplots_1_1plots_1_1_pose.html", "d4/dc9/classplots_1_1plots_1_1_pose" ],
        [ "Position", "d3/d6d/classplots_1_1plots_1_1_position.html", "d3/d6d/classplots_1_1plots_1_1_position" ]
      ] ]
    ] ],
    [ "Adapter", "d3/d7f/class_adapter.html", "d3/d7f/class_adapter" ],
    [ "Cluster", "d2/d23/class_cluster.html", "d2/d23/class_cluster" ],
    [ "Clustering", "d9/d10/class_clustering.html", "d9/d10/class_clustering" ],
    [ "Cone", "d8/da1/class_cone.html", "d8/da1/class_cone" ],
    [ "ConeDifferentiation", "d7/d4e/class_cone_differentiation.html", "d7/d4e/class_cone_differentiation" ],
    [ "ConeMap", "dc/d59/struct_cone_map.html", "dc/d59/struct_cone_map" ],
    [ "DBSCAN", "df/d6a/class_d_b_s_c_a_n.html", "df/d6a/class_d_b_s_c_a_n" ],
    [ "DBSCANTest", "d8/d90/class_d_b_s_c_a_n_test.html", "d8/d90/class_d_b_s_c_a_n_test" ],
    [ "EufsAdapter", "d0/d1d/class_eufs_adapter.html", "d0/d1d/class_eufs_adapter" ],
    [ "ExecTimeTest", "df/d59/class_exec_time_test.html", "df/d59/class_exec_time_test" ],
    [ "ExecTimeTestEKFTests", "d2/dac/class_exec_time_test_e_k_f_tests.html", "d2/dac/class_exec_time_test_e_k_f_tests" ],
    [ "ExtendedKalmanFilter", "da/da6/class_extended_kalman_filter.html", "da/da6/class_extended_kalman_filter" ],
    [ "FsdsAdapter", "d7/d8e/class_fsds_adapter.html", "d7/d8e/class_fsds_adapter" ],
    [ "GlobalPathPlanner", "d2/da4/class_global_path_planner.html", "d2/da4/class_global_path_planner" ],
    [ "GroundRemoval", "dc/d84/class_ground_removal.html", "dc/d84/class_ground_removal" ],
    [ "ImuVelocityModel", "d2/d58/class_imu_velocity_model.html", "d2/d58/class_imu_velocity_model" ],
    [ "InspectionFunctions", "d4/d89/class_inspection_functions.html", "d4/d89/class_inspection_functions" ],
    [ "InspectionMission", "de/d3d/class_inspection_mission.html", "de/d3d/class_inspection_mission" ],
    [ "IntegrationTest", "d7/d4e/class_integration_test.html", "d7/d4e/class_integration_test" ],
    [ "InvalidMissionException", "d3/df9/class_invalid_mission_exception.html", "d3/df9/class_invalid_mission_exception" ],
    [ "LeastSquaresDifferentiation", "d7/d15/class_least_squares_differentiation.html", "d7/d15/class_least_squares_differentiation" ],
    [ "LeastSquaresDifferentiationTest", "de/d1e/class_least_squares_differentiation_test.html", "de/d1e/class_least_squares_differentiation_test" ],
    [ "LMNode", "dd/db3/class_l_m_node.html", "dd/db3/class_l_m_node" ],
    [ "LocalPathPlanner", "d3/da1/class_local_path_planner.html", "d3/da1/class_local_path_planner" ],
    [ "LongitudinalControl", "d4/de8/class_longitudinal_control.html", "d4/de8/class_longitudinal_control" ],
    [ "MotionModel", "db/d66/class_motion_model.html", "db/d66/class_motion_model" ],
    [ "MotionUpdate", "db/d6d/struct_motion_update.html", "db/d6d/struct_motion_update" ],
    [ "NormalVelocityModel", "d7/df9/class_normal_velocity_model.html", "d7/df9/class_normal_velocity_model" ],
    [ "ObservationData", "d9/d90/struct_observation_data.html", "d9/d90/struct_observation_data" ],
    [ "ObservationModel", "d7/d64/class_observation_model.html", "d7/d64/class_observation_model" ],
    [ "PathPoint", "d9/d32/class_path_point.html", "d9/d32/class_path_point" ],
    [ "PathSmoothing", "d7/db7/class_path_smoothing.html", "d7/db7/class_path_smoothing" ],
    [ "Perception", "de/d07/class_perception.html", "de/d07/class_perception" ],
    [ "PID", "d6/d5a/class_p_i_d.html", "d6/d5a/class_p_i_d" ],
    [ "Planning", "d9/db5/class_planning.html", "d9/db5/class_planning" ],
    [ "Pose", "d8/d11/struct_pose.html", "d8/d11/struct_pose" ],
    [ "Position", "d1/d26/struct_position.html", "d1/d26/struct_position" ],
    [ "Publisher", "df/d57/class_publisher.html", "df/d57/class_publisher" ],
    [ "RANSAC", "d6/dc3/class_r_a_n_s_a_c.html", "d6/dc3/class_r_a_n_s_a_c" ],
    [ "RANSACTest", "d8/d5a/class_r_a_n_s_a_c_test.html", "d8/d5a/class_r_a_n_s_a_c_test" ],
    [ "TestAdapter", "df/df3/class_test_adapter.html", "df/df3/class_test_adapter" ],
    [ "Track", "d6/d2c/class_track.html", "d6/d2c/class_track" ],
    [ "VehicleState", "de/dfe/struct_vehicle_state.html", "de/dfe/struct_vehicle_state" ]
];