/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};

/* mpc_impl_dae_fun:(i0[13],i1[13],i2[3],i3[0],i4[],i5[4])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a02=arg[0]? arg[0][2] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[0]? arg[0][4] : 0;
  a02=sin(a02);
  a06=(a05*a02);
  a04=(a04-a06);
  a00=(a00-a04);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a02=(a01*a02);
  a03=(a05*a03);
  a02=(a02+a03);
  a00=(a00-a02);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a02=arg[0]? arg[0][5] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a03=1.;
  a04=5.0000000000000000e-01;
  a06=5.;
  a06=(a01-a06);
  a06=tanh(a06);
  a06=(a06+a03);
  a06=(a04*a06);
  a03=(a03-a06);
  a07=3.4600000000000001e+01;
  a08=6.1860705882352943e+02;
  a09=8.0400000000000005e-01;
  a10=-1.2250000000000001e-01;
  a11=casadi_sq(a01);
  a10=(a10*a11);
  a12=(a09*a10);
  a13=1.5300000000000000e+00;
  a12=(a12/a13);
  a14=2.;
  a12=(a12/a14);
  a08=(a08-a12);
  a12=2.0000000000000001e-01;
  a15=240.;
  a16=arg[0]? arg[0][6] : 0;
  a17=(a15*a16);
  a17=(a12*a17);
  a17=(a17/a13);
  a17=(a17/a14);
  a18=arg[0]? arg[0][7] : 0;
  a19=(a15*a18);
  a12=(a12*a19);
  a19=1.2000000000000000e+00;
  a12=(a12/a19);
  a04=(a04*a12);
  a12=(a17+a04);
  a20=(a08-a12);
  a21=(a07*a20);
  a22=1.0150000000000001e+00;
  a23=arg[0]? arg[0][9] : 0;
  a24=(a22*a23);
  a25=arg[0]? arg[0][8] : 0;
  a26=cos(a25);
  a19=(a19*a02);
  a19=(a19/a14);
  a27=(a01-a19);
  a28=(a26*a27);
  a29=sin(a25);
  a30=7.2599999999999998e-01;
  a31=(a30*a02);
  a31=(a05+a31);
  a32=(a29*a31);
  a28=(a28+a32);
  a24=(a24-a28);
  a28=casadi_sq(a28);
  a33=2.5000000000000000e-01;
  a28=(a28+a33);
  a28=sqrt(a28);
  a24=(a24/a28);
  a21=(a21*a24);
  a21=(a03*a21);
  a28=1.7749999999999999e+00;
  a34=(a28*a20);
  a35=1.6250000000000000e+00;
  a36=12.;
  a24=(a36*a24);
  a37=2.9999999999999999e-01;
  a38=atan(a24);
  a38=(a24-a38);
  a38=(a37*a38);
  a24=(a24-a38);
  a24=atan(a24);
  a24=(a35*a24);
  a24=sin(a24);
  a34=(a34*a24);
  a34=(a06*a34);
  a21=(a21+a34);
  a34=6.3661977236758138e-01;
  a24=1.4999999999999999e-02;
  a38=(a24*a20);
  a23=atan(a23);
  a38=(a38*a23);
  a38=(a34*a38);
  a21=(a21-a38);
  a38=(a21*a26);
  a23=1.6000000000000001e+00;
  a20=(a23*a20);
  a39=1.3899999999999999e+00;
  a40=9.6300000000000008e+00;
  a41=casadi_sq(a27);
  a41=(a41+a33);
  a41=sqrt(a41);
  a42=atan2(a31,a41);
  a42=(a25-a42);
  a42=(a40*a42);
  a43=9.4999999999999996e-01;
  a44=atan(a42);
  a44=(a42-a44);
  a44=(a43*a44);
  a42=(a42-a44);
  a42=atan(a42);
  a42=(a39*a42);
  a42=sin(a42);
  a20=(a20*a42);
  a42=(a20*a29);
  a38=(a38-a42);
  a42=(a04-a17);
  a08=(a08+a42);
  a42=(a07*a08);
  a44=arg[0]? arg[0][10] : 0;
  a45=(a22*a44);
  a19=(a01+a19);
  a46=(a26*a19);
  a46=(a46+a32);
  a45=(a45-a46);
  a46=casadi_sq(a46);
  a46=(a46+a33);
  a46=sqrt(a46);
  a45=(a45/a46);
  a42=(a42*a45);
  a42=(a03*a42);
  a46=(a28*a08);
  a45=(a36*a45);
  a32=atan(a45);
  a32=(a45-a32);
  a32=(a37*a32);
  a45=(a45-a32);
  a45=atan(a45);
  a45=(a35*a45);
  a45=sin(a45);
  a46=(a46*a45);
  a46=(a06*a46);
  a42=(a42+a46);
  a46=(a24*a08);
  a44=atan(a44);
  a46=(a46*a44);
  a46=(a34*a46);
  a42=(a42-a46);
  a46=(a42*a26);
  a08=(a23*a08);
  a44=casadi_sq(a19);
  a44=(a44+a33);
  a44=sqrt(a44);
  a31=atan2(a31,a44);
  a31=(a25-a31);
  a31=(a40*a31);
  a33=atan(a31);
  a33=(a31-a33);
  a33=(a43*a33);
  a31=(a31-a33);
  a31=atan(a31);
  a31=(a39*a31);
  a31=sin(a31);
  a08=(a08*a31);
  a31=(a08*a29);
  a46=(a46-a31);
  a31=(a38+a46);
  a33=5.5859294117647062e+02;
  a10=(a30*a10);
  a10=(a10/a13);
  a10=(a10/a14);
  a33=(a33-a10);
  a17=(a17-a04);
  a17=(a33+a17);
  a04=(a07*a17);
  a10=arg[0]? arg[0][11] : 0;
  a14=(a22*a10);
  a14=(a14-a27);
  a14=(a14/a41);
  a04=(a04*a14);
  a04=(a03*a04);
  a27=(a28*a17);
  a14=(a36*a14);
  a13=atan(a14);
  a13=(a14-a13);
  a13=(a37*a13);
  a14=(a14-a13);
  a14=atan(a14);
  a14=(a35*a14);
  a14=sin(a14);
  a27=(a27*a14);
  a27=(a06*a27);
  a04=(a04+a27);
  a27=(a24*a17);
  a10=atan(a10);
  a27=(a27*a10);
  a27=(a34*a27);
  a04=(a04-a27);
  a31=(a31+a04);
  a33=(a33+a12);
  a07=(a07*a33);
  a12=arg[0]? arg[0][12] : 0;
  a22=(a22*a12);
  a22=(a22-a19);
  a22=(a22/a44);
  a07=(a07*a22);
  a03=(a03*a07);
  a28=(a28*a33);
  a36=(a36*a22);
  a22=atan(a36);
  a22=(a36-a22);
  a37=(a37*a22);
  a36=(a36-a37);
  a36=atan(a36);
  a35=(a35*a36);
  a35=sin(a35);
  a28=(a28*a35);
  a06=(a06*a28);
  a03=(a03+a06);
  a24=(a24*a33);
  a12=atan(a12);
  a24=(a24*a12);
  a34=(a34*a24);
  a03=(a03-a34);
  a31=(a31+a03);
  a34=3.6749999999999999e-01;
  a34=(a34*a11);
  a31=(a31-a34);
  a31=(a31/a15);
  a34=(a02*a05);
  a34=(a31+a34);
  a00=(a00-a34);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a20=(a20*a26);
  a34=(a21*a29);
  a20=(a20+a34);
  a08=(a08*a26);
  a29=(a42*a29);
  a08=(a08+a29);
  a29=(a20+a08);
  a17=(a23*a17);
  a09=(a09*a02);
  a05=(a05-a09);
  a41=atan2(a05,a41);
  a41=(a40*a41);
  a09=(-a41);
  a09=atan(a09);
  a09=(a41+a09);
  a09=(a43*a09);
  a09=(a09-a41);
  a09=atan(a09);
  a09=(a39*a09);
  a09=sin(a09);
  a17=(a17*a09);
  a29=(a29+a17);
  a23=(a23*a33);
  a05=atan2(a05,a44);
  a40=(a40*a05);
  a05=(-a40);
  a05=atan(a05);
  a05=(a40+a05);
  a43=(a43*a05);
  a43=(a43-a40);
  a43=atan(a43);
  a39=(a39*a43);
  a39=sin(a39);
  a23=(a23*a39);
  a29=(a29+a23);
  a29=(a29/a15);
  a02=(a02*a01);
  a02=(a29-a02);
  a00=(a00-a02);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a20=(a30*a20);
  a02=5.9999999999999998e-01;
  a38=(a02*a38);
  a20=(a20-a38);
  a30=(a30*a08);
  a46=(a02*a46);
  a30=(a30+a46);
  a20=(a20+a30);
  a30=-8.0400000000000005e-01;
  a17=(a30*a17);
  a46=(a02*a04);
  a17=(a17-a46);
  a20=(a20+a17);
  a30=(a30*a23);
  a02=(a02*a03);
  a30=(a30+a02);
  a20=(a20+a30);
  a30=153.;
  a20=(a20/a30);
  a00=(a00-a20);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a31=(a31-a16);
  a16=10.;
  a31=(a31/a16);
  a00=(a00-a31);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a29=(a29-a18);
  a29=(a29/a16);
  a00=(a00-a29);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a29=arg[2]? arg[2][2] : 0;
  a29=(a29-a25);
  a25=1.0000000000000001e-01;
  a29=(a29/a25);
  a00=(a00-a29);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a29=2.0300000000000001e-01;
  a21=(a29*a21);
  a00=(a00+a21);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a42=(a29*a42);
  a00=(a00+a42);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a42=200.;
  a21=arg[2]? arg[2][0] : 0;
  a21=(a42*a21);
  a04=(a29*a04);
  a21=(a21-a04);
  a00=(a00-a21);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a21=arg[2]? arg[2][1] : 0;
  a42=(a42*a21);
  a29=(a29*a03);
  a42=(a42-a29);
  a00=(a00-a42);
  if (res[0]!=0) res[0][12]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int mpc_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpc_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
