#ifndef SRC_SPEED_EST_INCLUDE_UTILS_CAR_HPP_
#define SRC_SPEED_EST_INCLUDE_UTILS_CAR_HPP_

#define WHEEL_DIAMETER 0.5
#define WHEELBASE 1.530
#define REAR_AXIS_TO_CAMERA 0.79
#define AXIS_LENGTH 1.2

#endif  // SRC_SPEED_EST_INCLUDE_UTILS_CAR_HPP_