perception_adapter:
  ros__parameters:
    ransac_epsilon: 0.09
    ransac_n_neighbours: 40
    fov_trim: 45
    pc_max_range: 30.0
    clustering_n_neighbours: 1
    clustering_epsilon: 0.7
    horizontal_resolution: 0.33
    vertical_resolution: 0.2
    ground_removal: "grid_ransac"
    n_angular_grids: 2
    radius_resolution: 7.5
    target_file: "cone.pcd"
    max_correspondence_distance: 0.1
    max_iteration: 100
    transformation_epsilon: 1e-8
    euclidean_fitness_epsilon: 1e-6
    min_height: 0.13
    max_height: 0.4
    min_xoy: 0.0
    max_xoy: 0.3
    min_z: 0.00001
    max_z: 0.6
    min_z_score_x: -100000000.0
    max_z_score_x: 100000000000.0
    min_z_score_y: -1000000000.0
    max_z_score_y: 1000000000.0
