car:
  wheel_base: 1.535
  track_width: 1.2
  wheel_diameter: 0.406
  sprung_mass: 143
  unsprung_mass: 34
  total_mass: 177
  sprung_cg_y: 0.726
  sprung_cg_z: 0.245
  unsprung_cg_y: 0.765
  unsprung_cg_z: 0.206
  cg_height: 0.290
  cg_2_rear_axis: 0.6885
  gear_ratio: 12.5882
  Izz: 101.082
  front_bearing_drag: 0.25