aero:
  lift_coefficient: 4 # previous: 2.51555
  drag_coefficient: 1.41946 # previous: 2
  aero_balance_front: 0.631047 # previous: 0.391613
  frontal_area: 0.44
  air_density: 1.225
  aero_side_force_coefficient: 0.0
