transmission:
  gear_ratio: 3.67
  efficiency: 0.999 # original: 0.95
  kv: 9.24 # original: 40.0
  t_max: 542.25 # original: 300.0
  viscous_drag_coeff: 0 # original: 0.01
  coulomb_drag: 0 # original: 2.0
  coulomb_smooth_stiffness: 19.9294  # Stiffness for smoothing in Coulomb drag
