invictasim:
  # Simulator config
  input_adapter: "ros"  # Options: "ros", "keyboard"
  output_adapter: "ros"  # Options: "ros"
  vehicle_model: "FSFEUP02"  # Options: "FSFEUP02"
  sim_frequency: 1000  # Hz 
  track_name: "FSG25"  # Options: "Acceleration", "Skidpad", "FSG25", "FSG24", "FSG23", "FSE24", "FSE23", "EnduranceFSG25", "FSS22V1", "FSS22V2"
  publish_frequencies:
    tire: 100
    battery: 30
    motor: 30
    differential: 30
    aero: 30
    load_transfer: 30
    status: 100
    execution_times: 30
    track: 5
    visualization: 60