ekf_state_est:
  ros__parameters:
    data_association_limit_distance: 20.0
    sml_initial_limit: 0.1
    sml_curvature: 15.0
    observation_noise: 0.01
    wheel_speed_sensor_noise: 0.1
    motion_model: "normal_velocity_model"
    use_odometry: True
