cpplint \
    --exclude=./loc_map/include/Eigen/* \
    --exclude=./can/include/fs-ai_api/* \
    --exclude=./can/src/fs-ai_api/* \
    --exclude=./ros_can/* \
    --exclude=./build/* \
    --exclude=./install/* \
    --exclude=./log/* \
    --recursive . 