tuning:
  vehicle_model: "inline_02"
  csvs:
    - path: "FEUP_trackdrive.csv"
      weight: 1.0
    - path: "skidpad.csv"
      weight: 0.35
  score:
    max_distance_error: 1.5
    max_velocity_error: 2.0
  optimizer:
    algorithm: "simulated_annealing"
    iterations: 1
    mutation_scale: 0.02
    seed: 67
  parameters:
    - name: "tire.effective_tire_r"
      min: 0.19
      max: 0.23
