name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPPCHECK_OUTPUT: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt install cppcheck

      - name: Run cppcheck
        id: cmd
        run: cppcheck --enable=all src/

      - run: echo CPPCheck failed 
        if: ${{ steps.cmd.outputs.stderr }}