name: Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt install cppcheck
          pip install cpplint
          pip install pylint
          pip install mypy

      - name: Run cppcheck
        run: ./static-tools.sh cppcheck

      - name: Run cpplint
        run: ./static-tools.sh cpplint

      - name: Run pylint
        run: ./static-tools.sh pylint

      - name: Run mypy
        run: ./static-tools.sh mypy