name: Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt install cppcheck

      - name: Run cppcheck
        run: ./static-tools.sh cppcheck

  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: ./static-tools.sh cpplint